config/routes.rb
Rails.application.routes.draw do
  root 'boxes#index'

  resources :suggestions

  resources :boxes

end

app/models/box.rb
class Box < ActiveRecord::Base
obfuscate_id :spin => 666

  has_many :suggestions

  validates :text, presence: true
  validates :limit, presence: true

  def remaining
    self.limit - self.suggestions.count
  end
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :box

  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @suggestion = Suggestion.new
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)
    @box.text = nil if @box.text.blank?

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { redirect_to new_box_path, notice: 'no blank boxes'}
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)
    @suggestion.text = nil if @suggestion.text.blank?
    @box = @suggestion.box
    
    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @box, notice: 'added "' + @suggestion.text + '"' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { redirect_to @box, notice: 'don\'t put blank in the box' }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params
      params.require(:suggestion).permit(:text, :box_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1 class='heading'>Sugebox</h1>
<%= button_to "new box", :new_box, {method: :get, class: 'new-box-button'}%>

app/views/boxes/new.html.erb
<h1 class='heading'>New Box</h1>

<%= form_for(@box) do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text, :class=>'input-text effect1'%>
  <br></br>
  <%= f.submit "create", :class=>'create-button button-effect'%>
<% end %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div class='heading'>
    <%= @box.text %>
  </div>
</p>

<% if @box.remaining > 0 %>
  <%= form_for(@suggestion) do |f| %>
    <%= f.label :text %>
    <%= f.text_field :text, :autofocus=>true, :class=>'input-text effect1'%>
    <%= f.hidden_field :box_id, :value=> @box.id %>
    <br></br>
    <%= f.submit "put it in the box", :class=>'create-button button-effect'%>
  <% end %>

  <div class='limit-remaining'>
    needs <%= @box.remaining.to_words %> more to open
  </div>
<% else %>
  <ul class='suggestion-list'>
    <% @box.suggestions.each do |suggestion| %>
      <li class='suggestion-item'>
        <%= suggestion.text %>
      </li>
    <% end %>
  </ul>
  <%= button_to "new box", :new_box, {method: :get, class: 'new-box-button'}%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sugebox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1>Listing suggestions</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.text %></td>
        <td><%= link_to 'Show', suggestion %></td>
        <td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
        <td><%= link_to 'Destroy', suggestion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suggestion', new_suggestion_path %>

app/views/suggestions/new.html.erb
<h1>New suggestion</h1>

<%= render 'form' %>

<%= link_to 'Back', suggestions_path %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @suggestion.text %>
</p>

<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>